AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Beta version of the Netrunner slackbot
Resources:
  BetaNetrunnerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python2.7
      CodeUri: ./
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /BetaNetrunnerBotFunction
            Method: GET
